#!/usr/bin/env node
// Generates `src/_version.ts` from `package.json` so the TS code has a
// single, build-pinned source of truth for the package version. Without
// this, the version literal in `plugin.ts` (used as the iframe `?v=` cache
// buster) would drift from `package.json` (used by hatch-nodejs-version
// to stamp the wheel) — a classic three-place-keep-in-sync trap.

import { promises as fs } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const PKG = path.resolve(__dirname, '..', 'package.json')
const OUT = path.resolve(__dirname, '..', 'src', '_version.ts')

async function main() {
  const pkg = JSON.parse(await fs.readFile(PKG, 'utf8'))
  if (!pkg.version || typeof pkg.version !== 'string') {
    throw new Error(`sync-version: package.json missing string "version" field`)
  }
  const body = `// AUTO-GENERATED by scripts/sync-version.mjs from package.json.
// Do not edit by hand and do not commit — this file is in .gitignore.
export const PACKAGE_VERSION = ${JSON.stringify(pkg.version)} as const
`
  await fs.mkdir(path.dirname(OUT), { recursive: true })
  await fs.writeFile(OUT, body, 'utf8')
  console.log(`[sync-version] wrote ${path.relative(process.cwd(), OUT)} (version=${pkg.version})`)
}

main().catch(err => {
  console.error('[sync-version] failed:', err)
  process.exit(1)
})
