import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores([
    'dist',
    // Generated by vitest --coverage. Present locally but CI runs lint
    // before tests so it's never there on CI — if we don't exclude it
    // here, local lint OOMs on the istanbul HTML report.
    'coverage',
    // Downloaded VS Code install used by wdio extension tests. Gitignored,
    // so never on CI, but massive and full of .d.ts/.js files that explode
    // lint with thousands of errors.
    'vscode-extension/.wdio-vscode-service',
    // Python virtualenv for the JupyterLab package. Full of third-party
    // bundled JS (galata, yarn/handlebars staging templates) that trips the
    // parser (#each) and references removed rules (ban-types). Never ours.
    '.venv-jupyter',
    // Other gitignored build outputs that could show up locally.
    'cli/dist',
    'dist-e2e',
    'dist-ssr',
    'playwright-report',
    'test-results',
    '**/*.min.js',
    // Bundled build artifact (markmap-lib + friends inlined so the plugin
    // works on a fresh install with no node_modules — see Task 12). Carries
    // third-party inline eslint-disable directives for rules this repo's
    // flat config doesn't define, which ESLint reports as errors. A separate
    // CI step rebuilds it and diffs against git, so lint coverage here would
    // be redundant, not lost. Do not hand-edit; see claude-code-plugin's
    // build script.
    'claude-code-plugin/hook.mjs',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    rules: {
      // Honour the `_`-prefix convention for intentionally-unused vars/args
      // (e.g. iframe-bridge handlers that ignore their payload).
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // The JupyterLab package ships Lumino widgets, not a Vite fast-refresh
    // app, so the "only export components" constraint doesn't apply there.
    files: ['packages/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },
])
