import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores([
    'dist',
    // Generated by vitest --coverage. Present locally but CI runs lint
    // before tests so it's never there on CI — if we don't exclude it
    // here, local lint OOMs on the istanbul HTML report.
    'coverage',
    // Downloaded VS Code install used by wdio extension tests. Gitignored,
    // so never on CI, but massive and full of .d.ts/.js files that explode
    // lint with thousands of errors.
    'vscode-extension/.wdio-vscode-service',
    // Other gitignored build outputs that could show up locally.
    'cli/dist',
    'dist-e2e',
    'dist-ssr',
    'playwright-report',
    'test-results',
    '**/*.min.js',
  ]),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
])
