import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdtemp, rm, writeFile, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { writeOutputsIfChanged } from '../src/apply'

const MARKER = '<!-- generated by md-reader github-integration · do not edit -->\n'

let root: string
beforeEach(async () => { root = await mkdtemp(join(tmpdir(), 'mdr-apply-')) })
afterEach(async () => { await rm(root, { recursive: true, force: true }) })

describe('writeOutputsIfChanged', () => {
  it('creates a missing companion file', async () => {
    const changed = await writeOutputsIfChanged([
      { path: join(root, 'foo.md.comments.md'), content: 'hello\n' },
    ])
    expect(changed).toEqual([join(root, 'foo.md.comments.md')])
    expect(await readFile(join(root, 'foo.md.comments.md'), 'utf8')).toBe('hello\n')
  })

  it('skips writing when content is identical', async () => {
    const path = join(root, 'foo.md.comments.md')
    await writeFile(path, MARKER + 'same\n')
    const changed = await writeOutputsIfChanged([{ path, content: MARKER + 'same\n' }])
    expect(changed).toEqual([])
  })

  it('overwrites when content differs', async () => {
    const path = join(root, 'foo.md.comments.md')
    await writeFile(path, MARKER + 'old\n')
    const changed = await writeOutputsIfChanged([{ path, content: MARKER + 'new\n' }])
    expect(changed).toEqual([path])
    expect(await readFile(path, 'utf8')).toBe(MARKER + 'new\n')
  })

  it('deletes existing file when content is empty string and file has our marker', async () => {
    const path = join(root, 'foo.md.comments.md')
    await writeFile(path, MARKER + 'stale\n')
    const changed = await writeOutputsIfChanged([{ path, content: '' }])
    expect(changed).toEqual([path])
    await expect(readFile(path, 'utf8')).rejects.toThrow()
  })

  it('is a no-op when target is already absent and content is empty', async () => {
    const changed = await writeOutputsIfChanged([
      { path: join(root, 'never-existed.md.comments.md'), content: '' },
    ])
    expect(changed).toEqual([])
  })

  it('refuses to overwrite a hand-written companion file (no marker)', async () => {
    const path = join(root, 'foo.md.comments.md')
    await writeFile(path, '# my notes\n')
    await expect(
      writeOutputsIfChanged([{ path, content: MARKER + 'something\n' }])
    ).rejects.toThrow(/refusing to overwrite/)
    // Original file is untouched
    expect(await readFile(path, 'utf8')).toBe('# my notes\n')
  })

  it('refuses to delete a hand-written file even when content is empty', async () => {
    const path = join(root, 'foo.md.comments.md')
    await writeFile(path, '# my hand-written notes\n')
    const changed = await writeOutputsIfChanged([{ path, content: '' }])
    // No change — hand-written file is preserved
    expect(changed).toEqual([])
    expect(await readFile(path, 'utf8')).toBe('# my hand-written notes\n')
  })

  it('still overwrites when existing content has the marker', async () => {
    const path = join(root, 'foo.md.comments.md')
    await writeFile(path, MARKER + 'old content\n')
    const changed = await writeOutputsIfChanged([{ path, content: MARKER + 'new content\n' }])
    expect(changed).toEqual([path])
    expect(await readFile(path, 'utf8')).toBe(MARKER + 'new content\n')
  })
})
