import { readFile, writeFile, unlink, mkdir } from 'node:fs/promises'
import { dirname } from 'node:path'

export interface OutputFile {
  path: string
  /** Empty string means "remove the file if it exists". */
  content: string
}

const HEADER_MARKER = '<!-- generated by md-reader github-integration'

/**
 * Write each output only when its content differs from disk. Returns the list
 * of paths that were actually changed (created, updated, or deleted), so the
 * caller can decide whether to commit.
 *
 * Collision protection: refuses to overwrite (or delete) a file that was NOT
 * generated by this Action — i.e., a file that lacks the HEADER_MARKER on its
 * first line. This prevents silently nuking hand-written notes at the same path.
 */
export async function writeOutputsIfChanged(outputs: OutputFile[]): Promise<string[]> {
  const changed: string[] = []
  for (const { path, content } of outputs) {
    const existing = await readSafely(path)
    if (content === '') {
      if (existing !== null && existing.startsWith(HEADER_MARKER)) {
        await unlink(path)
        changed.push(path)
      } else if (existing !== null) {
        // Hand-written file — don't delete it. Skip silently.
        // The caller's try/catch (per-pair) will see no change here.
      }
      continue
    }
    if (existing !== null && !existing.startsWith(HEADER_MARKER)) {
      // Don't clobber a hand-authored file at our target path.
      throw new Error(`refusing to overwrite ${path}: existing file lacks the md-reader generation marker. Move or delete it to regenerate.`)
    }
    if (existing === content) continue
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, content, 'utf8')
    changed.push(path)
  }
  return changed
}

async function readSafely(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf8')
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null
    throw err
  }
}
