import type { DocState, MaterializedComment } from './parser'
import { resolveLine } from './anchor'

const HEADER = '<!-- generated by md-reader github-integration · do not edit -->'

/**
 * Produce the human-readable companion markdown. Returns '' when there are
 * no comments — caller treats that as "delete the companion if it existed".
 */
export function renderCommentsMarkdown(
  state: DocState,
  sourcePathRelative: string,
  sourceText: string,
): string {
  const all = [...state.comments.values()]
  if (all.length === 0) return ''

  // Highlights are intentionally omitted from the companion; they carry no
  // author-facing prose. If a future schema adds highlight notes that need
  // surfacing, render them here.

  const decorated = all.map((c) => ({
    c,
    line: resolveLine(c.anchor, sourceText),
  }))
  decorated.sort((a, b) => {
    // Open comments first, then resolved.
    const ar = a.c.resolved ? 1 : 0
    const br = b.c.resolved ? 1 : 0
    if (ar !== br) return ar - br
    const al = a.line ?? Number.MAX_SAFE_INTEGER
    const bl = b.line ?? Number.MAX_SAFE_INTEGER
    if (al !== bl) return al - bl
    return a.c.createdAt - b.c.createdAt
  })

  const total = decorated.length

  const parts: string[] = [
    HEADER,
    `# Comments on \`${sourcePathRelative}\``,
    '',
    `${total} ${total === 1 ? 'comment' : 'comments'}`,
    '',
    '---',
    '',
  ]

  for (const { c, line } of decorated) {
    parts.push(renderOne(c, line, sourcePathRelative))
    parts.push('')
    parts.push('---')
    parts.push('')
  }

  // Trim the trailing separator
  while (parts.length && (parts[parts.length - 1] === '' || parts[parts.length - 1] === '---')) {
    parts.pop()
  }
  return parts.join('\n') + '\n'
}

function renderOne(c: MaterializedComment, line: number | null, sourcePath: string): string {
  const lineLabel = line !== null ? `Line ${line}` : 'Unanchored'
  const link = line !== null ? `[Open in source](${sourcePath}#L${line})` : `[Open in source](${sourcePath})`
  const quote = quoteSnippet(c.selectedText)
  const stamp = formatDate(c.createdAt)
  const body = (c.body ?? '').trim()

  if (c.resolved) {
    return [
      '<details>',
      `<summary>Resolved · ${lineLabel} — ${quote}</summary>`,
      '',
      `**${escapeMd(c.author)}** · ${stamp}`,
      '',
      body,
      '',
      link,
      '</details>',
    ].join('\n')
  }

  return [
    `### ${lineLabel} — ${quote}`,
    '',
    `**${escapeMd(c.author)}** · ${stamp}`,
    '',
    body,
    '',
    link,
  ].join('\n')
}

function quoteSnippet(text: string): string {
  const trimmed = (text ?? '').trim().replace(/\s+/g, ' ')
  const max = 120
  const truncated = trimmed.length > max ? trimmed.slice(0, max - 1) + '…' : trimmed
  return `“${truncated}”`
}

function escapeMd(s: string): string {
  return s.replace(/[*_`[\]<>]/g, (m) => '\\' + m)
}

function formatDate(ms: number): string {
  // YYYY-MM-DD in UTC — deterministic across runners.
  const d = new Date(ms)
  const y = d.getUTCFullYear()
  const m = String(d.getUTCMonth() + 1).padStart(2, '0')
  const day = String(d.getUTCDate()).padStart(2, '0')
  return `${y}-${m}-${day}`
}
